# Generated by Django 5.2 on 2025-05-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensores',
            old_name='mac_adress',
            new_name='mac_address',
        ),
    ]
