# Generated by Django 5.2 on 2025-06-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_mac_adress_sensores_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(choices=[('U', 'Umidade'), ('T', 'Temperatura'), ('L', 'Luminosidade'), ('C', 'Contador')], default='T', max_length=50),
        ),
    ]
