# Generated by Django 5.2 on 2025-06-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sensores_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(choices=[('umidade', 'Umidade'), ('temperatura', 'Temperatura'), ('luminosidade', 'Luminosidade'), ('contador', 'Contador')], default='T', max_length=12),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='unidade_med',
            field=models.CharField(choices=[('°C', '°C'), ('Lux', 'Lux'), ('%', '%'), ('Num', 'Num')], default='°C', max_length=6),
        ),
    ]
